version: '3.8'
services:

    db:
        image: postgres:14.1-alpine
        network_mode: host
        restart: always
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
            # copy the sql script to create tables
            - ./sql/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
        environment:
            - POSTGRES_DB=dana
            - POSTGRES_USER=dana
            - POSTGRES_PASSWORD=dana123
        ports:
        - '5432:5432'

    engine:
        build: .
        network_mode: host
        container_name: engine
        depends_on:
            - db
        volumes:
            - ./script:/usr/local/dana_test/script
            - ./dataset:/usr/local/dana_test/dataset
            - ./helpers:/usr/local/dana_test/helpers
        stdin_open: true
        tty: true


volumes:
  db:
    driver: local
